name = "pokemon-sammlung"
main = "src/index.js"
account_id = "3eff4ed7c54a174af6d042c750ebee99" # nicht geheim; nötig fürs automatische Veröffentlichen per GitHub Action
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "pokemon-sammlung"
database_id = "a8fae683-d5c4-4469-8087-dcea378a8ea1"
migrations_dir = "migrations"

# Dev-Stufe (Branch develop): eigener Worker + eigene Datenbank. Aufruf mit --env dev.
[env.dev]
name = "pokemon-sammlung-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "pokemon-sammlung-dev"
database_id = "2de88fcf-125f-4480-9aee-37252ce298ba"
migrations_dir = "migrations"
